# הגדרת החיבור ל-MySQL ב-Clever Cloud
spring.datasource.url=jdbc:mysql://b3p6gsynqcm8p4frq1of-mysql.services.clever-cloud.com:3306/b3p6gsynqcm8p4frq1of?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=uy7ferrarnspaes5
spring.datasource.password=Xz8Bn7IhYhbt0NajD002

# הגדרת הדרייבר
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# הגדרות Hibernate - יצירת טבלאות ועדכון מבנה אוטומטי
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# הגדרה לפורט של השרת (חשוב להעלאה ל-Render בהמשך)
server.port=${PORT:8080}